- name: Déploiement VM avec Ansible
  hosts: vcenter
  gather_facts: no
  tasks:
    - name: Créer une VM
      community.vmware.vmware_guest:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
        datacenter: "DC01"
        cluster: "Cluster01"
        name: "Demo-VM-Ansible"
        template: "Ubuntu-Template"
        state: poweredon
        networks:
          - name: "VM Network"
        hardware:
          memory_mb: 2048
          num_cpus: 2
        disk:
          - size_gb: 20
            type: thin
            datastore: "Datastore1"
